---
title: "RTS Distribution Model"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

# Load Libraries

```{r}
library(biomod2)
library(sf)
library(terra)
library(tidyterra)
library(viridis)
library(tidyverse)
```

```{r}
theme_set(theme_bw())
```


# Load Data

```{r}
pca = rast('./pca/pca.tif')

arts = st_read('../ARTS/ARTS_main_dataset/v.1.0.0/ARTS_main_dataset_v.1.0.0.geojson') |>
  distinct() |>
  st_make_valid() |>
  # keep one polygon per RTS only
  filter(CentroidLat == first(CentroidLat),
         .by = UID)

world = rnaturalearth::ne_countries(scale = "large", returnclass = "sf")
world = world |>
  st_transform(3413) |>
  st_crop(ext(pca))
```


# Aggregate RTS Delineations to Presence/Absence in 1 km Grid

Presence Data

```{r}
# arts_poly_rast = rasterizeGeom(
#   vect(arts %>%
#          filter(
#            TrainClass == 'Positive' &
#              (st_geometry_type(.) == 'POLYGON' | st_geometry_type(.) == 'MULTIPOLYGON'))
#   ), 
#   pca,
#   fun = 'count'
# )
# 
# arts_point_rast = rasterizeGeom(
#   vect(arts %>%
#          filter(
#            TrainClass == 'Positive' &
#              st_geometry_type(.) == 'POINT')
#   ), 
#   pca,
#   fun = 'count'
# )
# 
# arts_rast = arts_poly_rast + arts_point_rast
# 
# arts_rast = arts_rast |>
#   classify(matrix(c(0, NA), ncol = 2))
# # this can be run instead of classify to return 0 for all cells without observed RTS, but that is probably not a good way to do things since we know that there are actually RTS in many of the cells with 0
#   # mask(pca |>
#   #        subset(1))
# 
# # Convert to data frame
# arts_grid = arts_rast |>
#   as.data.frame(xy = TRUE, na.rm = TRUE) |>
#   mutate(rts = case_when(count >= 1 ~ 1,
#                            count == 0 ~ 0))
# 
# rm(arts_poly_rast, arts_point_rast)
```

Plot
geom_spatraster isn't great for displaying this data, because the summarizing used to make it plot faster makes a lot of the data look like it's not there

```{r}
# ggplot() +
#   geom_spatraster(data = arts_rast) +
#   geom_sf(data = arts,
#           linewidth = 0.25,
#           size = 0.25,
#           color = 'black',
#           fill = 'transparent') +
#   scale_fill_viridis(na.value = 'transparent') +
#   coord_sf(expand = FALSE)
# 
# ggplot() +
#   geom_spatraster(
#     data = arts_rast |>
#       crop(ext(-800000, -650000, -900000, -750000))
#     ) +
#   geom_sf(
#     data = arts |>
#       st_crop(
#         st_bbox(
#           c(
#             xmin = -800000, 
#             xmax = -650000, 
#             ymin = -900000, 
#             ymax = -750000
#           )
#         )
#       ),
#     linewidth = 0.25,
#     size = 0.25,
#     color = 'black',
#     fill = 'transparent'
#     ) +
#   scale_fill_viridis(na.value = 'transparent') +
#   coord_sf(
#     # xlim = c(-800000, -650000),
#     # ylim = c(-900000, -750000),
#     expand = FALSE
#     )

```

Absence Data

```{r}
# arts_neg_rast = rasterize(
#   vect(arts %>%
#          filter(TrainClass == 'Negative')), 
#   pca
# )
# 
# arts_neg_rast = arts_neg_rast |>
#   classify(matrix(c(1, 0), ncol = 2, byrow = TRUE))
# 
# # Make sure that negative 1 km cells don't have any observed RTS in them outside of the negative bounding box
# arts_neg_rast[arts_neg_rast == 0 & !is.na(arts_rast)] = NA
# 
# # Convert to data frame
# arts_neg_grid = arts_neg_rast |>
#   as.data.frame(xy = TRUE, na.rm = TRUE) |>
#   rename(count = layer) |>
#   mutate(rts = count)
```

Combine Presence and Absence Data

```{r}
# arts_grid = arts_grid |>
#   bind_rows(arts_neg_grid)
```

# Format Data for SDM

```{r}
# arts_biomod = BIOMOD_FormatingData(
#   resp.var = arts_grid |> pull(rts),
#   expl.var = pca |> subset(1:6),
#   resp.xy = arts_grid |> select(x, y),
#   resp.name = 'rts'
# )
# 
# saveRDS(arts_biomod, './sdm/arts_biomod_v.1.0.0.rds')
arts_biomod = readRDS('./sdm/arts_biomod_v.1.0.0.rds')
```

# Run Models

```{r}
print(Sys.time())
opt.d = bm_ModelingOptions(
  data.type = 'binary',
  models = "GBM",
  strategy = 'default'
)

print(Sys.time())
cv_kfold = bm_CrossValidation(
  arts_biomod,
  strategy = 'kfold',
  nb.rep = 1,
  k = 10,
  do.full.models = TRUE
)

print(Sys.time())
tuned.gbm = bm_Tuning(
  model = "GBM",
  tuning.fun = "gbm", ## see in ModelsTable
  bm.options = opt.d@options$GBM.binary.gbm.gbm,
  do.formula = FALSE,
  bm.format = arts_biomod,
  calib.lines = cv_kfold
)

print(Sys.time())
```

```{r}
print(Sys.time())
opt.t = bm_ModelingOptions(
  data.type = 'binary',
  models = "GBM",
  strategy = "user.defined",
  user.val = list(GBM.binary.gbm.gbm = tuned.gbm),
  user.base = "bigboss",
  bm.format = arts_biomod,
  calib.lines = cv_kfold
)
print(Sys.time())

rts_model= BIOMOD_Modeling(
  arts_biomod,
  modeling.id = "GBM 10 K-fold Validation Tuned",
  models = c("GBM"),
  CV.strategy = "user.defined",
  CV.user.table = cv_kfold,
  OPT.strategy = "user.defined",
  OPT.user = opt.t,
  metric.eval = c('TSS','ROC'),
  seed.val = 42,
  nb.cpu = 19
)

print(Sys.time())
```

```{r}
saveRDS(rts_model,
        './sdm/rts_gbm_kfold_10_tuned.rds')


# rts_model = readRDS('./sdm/rts_gbm_kfold_10_tuned.rds')
```

```{r}
# Get evaluation scores & variables importance
get_evaluations(rts_model)
get_variables_importance(rts_model)

# Represent evaluation scores & variables importance
bm_PlotEvalMean(bm.out = rts_model)
bm_PlotEvalBoxplot(bm.out = rts_model, group.by = c('algo', 'algo'))
bm_PlotEvalBoxplot(bm.out = rts_model, group.by = c('algo', 'run'))
bm_PlotVarImpBoxplot(bm.out = rts_model, group.by = c('expl.var', 'algo', 'algo'))
bm_PlotVarImpBoxplot(bm.out = rts_model, group.by = c('expl.var', 'algo', 'run'))
bm_PlotVarImpBoxplot(bm.out = rts_model, group.by = c('algo', 'expl.var', 'run'))

# Represent response curves
bm_PlotResponseCurves(bm.out = rts_model,
                      models.chosen = get_built_models(rts_model)[c(1:3, 12:14)],
                      fixed.var = 'median')
bm_PlotResponseCurves(bm.out = rts_model,
                      models.chosen = get_built_models(rts_model)[c(1:3, 12:14)],
                      fixed.var = 'min')
bm_PlotResponseCurves(bm.out = rts_model,
                      models.chosen = get_built_models(rts_model)[3],
                      fixed.var = 'median',
                      do.bivariate = TRUE)
```

```{r}
print(Sys.time())
rts_pred <- BIOMOD_Projection(
  bm.mod = rts_model,
  proj.name = 'Current',
  new.env = pca,
  models.chosen = 'all',
  # models.chosen = 'rts_allData_allRun_GBM',
  metric.binary = 'all',
  metric.filter = 'all',
  build.clamping.mask = TRUE,
  nb.cpu = 19
)
print(Sys.time())
# rts_pred
plot(rts_pred)
```

```{r}
saveRDS(rts_pred,
        './sdm/rts_gbm_kfold_10_pred_tuned.rds')

# rts_pred = readRDS('./sdm/rts_gbm_kfold_10_pred_tuned.rds')
```

```{r}
rts_susceptibility = rast('./rts/proj_Current/proj_Current_rts.tif')

# plot(rts_pred) +
#   # geom_sf(data = world, fill = 'transparent') +
#   scale_fill_viridis(na.value = 'transparent') +
#   coord_sf(expand = FALSE)

ggplot() +
  geom_sf(data = world) +
  geom_spatraster(data = rts_susceptibility |> subset(11)) +
  scale_fill_viridis(na.value = 'transparent') +
  coord_sf(expand = FALSE)

ggsave('./figures/gbm_kfold_10_pred_all_tuned.jpg',
       height = 5,
       width = 6.5)
```

