---
title: "Analyze RTS Susceptibility Results"
author: "Heidi Rodenhizer"
date: '`r Sys.Date()`'
output: html_document
---

# Load Packages

```{r}
library(terra)
library(tidyterra)
library(sf)
library(viridis)
library(tidyverse)
```

```{r}
theme_set(theme_bw())
```


# Load Data

```{r}
rts_susceptibility = rast('./sdm/gbm_kfold_10_pred_tuned_combined_class_v.1.0.1.tif')
rts_susceptibility_m = rast('../makopoulou_data/Susceptibility_Map.tif') |>
  project(rts_susceptibility, method = 'near')
```

```{r}
arts = st_read('../ARTS/ARTS_main_dataset/v.1.0.1/ARTS_main_dataset_v.1.0.1.geojson')
pca = rast('./pca/pca.tif')
```

```{r}
files = list.files(
  '../makopoulou_data/RTS_presences_not_in_ARTS',
  full.names = TRUE,
  recursive = TRUE,
  pattern = '\\.shp$'
)
files = files[which(!str_detect(files, 'Couture.+((MVLSD)|(ald))'))]
rts_not_in_arts = map_dfr(
  files,
  ~ .x |>
    st_read() |>
    select(geometry) |>
    mutate(source = str_split_i(.x, '/', i = -1)) |>
    st_transform(crs = 3413)
) |>
  st_as_sf()
```

```{r}
world = rnaturalearth::ne_countries(scale = "large", returnclass = "sf")
world = world |>
  st_transform(3413) |>
  st_crop(ext(rts_susceptibility))
```


# Difference Map

```{r}
rts_susceptibility_diff = rts_susceptibility_m - rts_susceptibility
```

## Map Difference

```{r}
ggplot() +
  geom_sf(data = world) +
  geom_spatraster(
    data = rts_susceptibility_diff,
    maxcell = 1e+07
  ) +
  scale_fill_gradient2(
    name = expression(Delta~'RTS Susceptibility'),
    limits = c(-5, 5),
    low = '#0066CC',
    mid = '#FFFFDD',
    high = '#990000',
    na.value = 'transparent'
  ) +
  coord_sf(expand = FALSE) +
  ggtitle('RTS Susceptibility Difference (Makopoulou - Woodwell)')
```

```{r}
ggplot() +
  geom_sf(data = world) +
  geom_spatraster(
    data = rts_susceptibility_diff,
    maxcell = 1e+07
  ) +
  scale_fill_gradient2(
    name = expression(Delta~' RTS Susceptibility'),
    limits = c(-5, 5),
    low = '#0066CC',
    mid = '#FFFFDD',
    high = '#990000',
    na.value = 'transparent'
  ) +
  geom_sf(
    data = rts_not_in_arts, 
    aes(color = ''), 
    size = 0.3
    ) +
  scale_color_manual(
    name = 'RTS Not in ARTS',
    values = c('black')
    ) +
  coord_sf(expand = FALSE) +
  ggtitle('RTS Susceptibility Difference (Makopoulou - Woodwell)')

# ggsave('./figures/rts_susceptibility_diff.jpg',
#        height = 6,
#        width = 8)
```


## Explore Regions of Highest Divergence

```{r}
rts_susceptibility_diff_extremes = rts_susceptibility_diff |>
  classify(
  rcl = matrix(
    c(-6, -2.5, -1,
      -2.5, 2.5, NA,
      2.5, 6, 1),
  ncol = 3,
  byrow = TRUE
  )
)

levels(rts_susceptibility_diff_extremes) = tibble(
  id = c(-1, 1),
  susceptibility_class = c('<= -3',
                           '>= 3')
)
```

```{r}
ggplot() +
  geom_sf(data = world) +
  geom_spatraster(
    data = rts_susceptibility_diff_extremes,
    maxcell = 1e+07
  ) +
  scale_fill_manual(
    name = 'Difference',
    values = c('#0066CC', '#990000'),
    na.value = 'transparent',
    na.translate = FALSE
  ) +
  coord_sf(expand = FALSE) +
  ggtitle('RTS Susceptibility Difference (Makopoulou - Woodwell)')
```

Taking a look at the top 3 predictors of RTS in our model
```{r}
ggplot() +
  geom_sf(data = world) +
  geom_spatraster_rgb(
    data = pca,
    r = 1,
    g = 2,
    b = 5,
    max_col_value = 7
  ) +
  # geom_sf(data = rts_susceptibility_diff_extremes_poly,
  #         aes(color = susceptibility_class),
  #         fill = 'transparent') +
  coord_sf(expand = FALSE) +
  ggtitle('Principal Components 1, 2, and 5 as RGB')
```

```{r}
rts_susceptibility_diff_df = as.data.frame(
  rts_susceptibility_diff,
  xy = TRUE
) |>
  filter(!is.na(Susceptibility_Map))

pca_df = pca[[1:6]] |>
  as.data.frame(
    xy = TRUE
  ) |>
  filter(!is.na(PC1))

rts_pca_df = rts_susceptibility_diff_df |>
  left_join(pca_df,
            by = c('x', 'y'))

```

```{r}
rts_pca_df_subset = rts_pca_df |>
  filter(abs(Susceptibility_Map) >= 3) |>
  pivot_longer(PC1:PC6, names_to = 'pc', values_to = 'value')
```

```{r}
ggplot(rts_pca_df_subset,
       aes(x = pc, y = value, color = Susceptibility_Map)) +
  geom_boxplot(position = position_dodge())
```

