---
title: "5_input_data_compile_and_crop"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

# Load Libraries

```{r}
library(terra)
library(tidyterra)
library(sf)
library(lwgeom)
library(viridis)
library(ggthemes)
library(tidyverse)
```

```{r}
theme_set(theme_bw())
```


# Load Extent

```{r}
roi = st_read('./input_data/OlefeldtThermokarstMap/study_extent_buff500.shp')

# Transforming the CRS from a polar projection to WGS84 causes
# incorrect polygons where Russia crosses the 180th meridian.
# Remove a polygon extending from -180 to 180 prior to 
# transforming the CRS to solve this problem.
# Order of the points matters for whether this is a polygon of
# infinite thinness (current) or whole globe (not as written)
split_poly = st_sfc(
      st_polygon(list(matrix(c(180, 0, 
                          -180, 0,
                          -180, 90,
                          180, 90,
                          180, 0), 
                        ncol = 2,
                        byrow = TRUE))),
      crs = 'EPSG:4326'
    ) |>
      st_transform(crs = st_crs(roi))

roi_4326 = roi |>
  st_cast('POLYGON') |>
  st_difference(split_poly) |>
  st_transform('EPSG:4326')

roi = roi |>
  st_transform(crs = 3413)
```

```{r}
ggplot(roi) +
  geom_sf() +
  coord_sf(expand = FALSE)

ggplot(roi_4326) +
  geom_sf() +
  coord_sf(expand = FALSE)
```


# Load Raster Data

## TerraClimate

```{r}
terraclimate = rast('./input_data/TerraClimate/TerraClimateCompiled.tif') |>
  crop(roi_4326) |>
  mask(roi_4326)
```

```{r}
terraclimate = terraclimate |>
  project(y = 'EPSG:3413',
          res = 1000,
          method = 'bilinear')
```

```{r}
map(
  names(terraclimate),
  ~ ggplot() +
  geom_spatraster(
    data = terraclimate |>
         subset(.x)
    ) +
  scale_fill_viridis(name = .x,
                     na.value = 'transparent') +
  facet_wrap(~lyr) +
  coord_sf(expand = FALSE)
)
```


## Copernicus Topography

```{r}
coptopo = rast('./input_data/Copernicus_DEM/CopernicusDEMCompiled.tif') |>
  crop(roi_4326) |>
  mask(roi_4326)

names(coptopo) = c('suitable_slope', 'suitable_tpi')
```

```{r}
coptopo = coptopo |>
  project(y = 'EPSG:3413',
          res = 1000,
          method = 'bilinear')
```

```{r}
map(
  names(coptopo),
  ~ ggplot() +
  geom_spatraster(
    data = coptopo |>
         subset(.x)
    ) +
  scale_fill_viridis(name = .x,
                     na.value = 'transparent') +
  facet_wrap(~lyr) +
  coord_sf(crs = 3413,
           expand = FALSE)
)

```


## MODIS LST

```{r}
modislst = rast('./input_data/MODIS_LST/MODISLSTCompiled.tif') |>
  crop(roi_4326) |>
  mask(roi_4326)
```

```{r}
modislst = modislst |>
  project(y = 'EPSG:3413',
          res = 1000,
          method = 'bilinear')
```


## NIEER Permafrost (Ran et al. 2022)

```{r}
files = list.files(
  './input_data/NIEERPermafrost/NIEER_permafrost_dataset_released', 
  full.names = TRUE,
  pattern = 'tif$'
)

nieer = files |>
  map(~rast(.x)) |>
  rast() |>
  crop(roi_4326) |>
  mask(roi_4326) |>
  project(terraclimate)

names(nieer) = c('alt', 'magt', 'permafrost_prob')
```

```{r}
nieer = nieer |>
  project(y = 'EPSG:3413',
          res = 1000,
          method = 'bilinear')
```

```{r}
map(
  names(nieer),
  ~ ggplot() +
  geom_spatraster(
    data = nieer |>
         subset(.x)
    ) +
  scale_fill_viridis(name = .x,
                     na.value = 'transparent') +
  facet_wrap(~lyr) +
  coord_sf(crs = 3413,
           expand = FALSE)
)

```


## Soil Grids

```{r}
soilgrids = rast('./input_data/SoilGridsV2/SoilGridsV2Compiled.tif') |>
  crop(roi_4326) |>
  mask(roi_4326)
```

```{r}
soilgrids = soilgrids |>
  project(y = 'EPSG:3413',
          res = 1000,
          method = 'bilinear')
```


# Load Vector Data

## Brown Permafrost

```{r}
brown = st_read('./input_data/BrownCircumArcticPermafrost/permaice.shp') 
brown = brown |>
  filter(CONTENT %in% c('l', 'm', 'h')) |>
  mutate(ice_content = case_when(CONTENT == 'l' ~ 1,
                             CONTENT == 'm' ~ 2,
                             CONTENT == 'h' ~ 3,
                             TRUE ~ 0)) |>
  st_transform(st_crs(terraclimate)) |>
  rasterize(terraclimate, field = 'ice_content', background = 0) |>
  mask(roi)
```

```{r}
ggplot() +
  geom_spatraster(data = brown) +
  scale_fill_viridis(name = 'Ice Content',
                     na.value = 'transparent') +
  coord_sf(expand = FALSE)
```


## Olefeldt Thermokarst Map

```{r}
thermokarst = st_read('./input_data/OlefeldtThermokarstMap/data/Circumpolar_Thermokarst_Landscapes_epsg3413.shp') |>
  mutate(hillslope_thermokarst = case_when(
    TKHP == 'High' ~ 3,
    TKHP == 'Moderate' ~ 2,
    TKHP == 'Low' ~ 1,
    TKHP == 'None' ~ 0,
    TRUE ~ 0
  )) |>
  st_transform(st_crs(terraclimate)) |>
  rasterize(terraclimate, field = 'hillslope_thermokarst', background = 0) |>
  mask(roi)
```

```{r}
ggplot() +
  geom_spatraster(data = thermokarst) +
  scale_fill_viridis(name = 'Thermokarst\nLandscapes ',
                     na.value = 'transparent') +
  coord_sf(expand = FALSE)
```


## Yedoma

```{r}
yedoma = st_read('./input_data/IRYP_v2_yedoma/IRYP_v2_yedoma_domain_Shapefile/IRYP_v2_yedoma_domain.shp') |>
  st_transform(st_crs(terraclimate)) |>
  rasterize(terraclimate, background = 0) |>
  mask(roi)
names(yedoma) <- c('yedoma_domain')
```

```{r}
ggplot() +
  geom_spatraster(
    data = yedoma |>
         subset('yedoma_domain')
    ) +
  scale_fill_viridis(name = 'Yedoma\nDomain',
                     na.value = 'transparent') +
  coord_sf(expand = FALSE)
```


# Combine All Layers

```{r}
rts_rep_data = c(
  terraclimate,
  coptopo,
  modislst,
  nieer,
  soilgrids,
  brown,
  thermokarst,
  yedoma
) |>
  mask(nieer[['alt']])
```

```{r}
rts_rep_rescale = scale(rts_rep_data)
```

```{r}
ggplot() +
  geom_spatraster(data = rts_rep_rescale) +
  scale_fill_viridis(name = 'z-score',
                     limits = c(-2, 2),
                     na.value = 'transparent',
                     oob = scales::squish) +
  facet_wrap(~ lyr, ncol = 5) +
  coord_sf(expand = FALSE) +
  theme(legend.position = 'bottom'#,
        # legend.position.inside = c(0.9, -0.01),
        # legend.justification.inside = c(0.5, 0),
        # legend.title.position = 'left',
        # legend.title = element_text(angle = 90, hjust = 0.5)
        )

# ggsave('./figures/input_layers.jpg',
#        height = 9,
#        width = 6.5)
# ggsave('./figures/input_layers.pdf',
#        height = 9,
#        width = 6.5)
```

```{r}
# writeRaster(rts_rep_data,
#             './input_data/rts_rep_input_data_3413.tif')
# writeRaster(rts_rep_rescale,
#             './input_data/rts_rep_input_data_rescale_3413.tif')
```

