---
title: "Environmental PCA"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

# Load Libraries

```{r}
library(terra)
library(tidyterra)
library(sf)
library(rnaturalearth)
library(viridis)
library(ggfortify)
library(tidyverse)
```

```{r}
theme_set(theme_bw())
```


# Load Input Data

```{r}
rts_rep_rescale = rast('./input_data/rts_rep_input_data_rescale_3413.tif')
```

```{r}
# Careful! This required about 52 Gb of memory during the conversion.
rts_rep_rescale_df = rts_rep_rescale |>
  as.data.frame(xy = TRUE, cell = TRUE, na.rm = TRUE)

# Make sure to "Free unused R memory" after running
gc()

nrow(rts_rep_rescale_df)
```

```{r}
world <- ne_countries(scale = "large", returnclass = "sf")

world_rast = world |>
  st_transform(crs(rts_rep_rescale)) |>
  rasterize(rts_rep_rescale, field = 'name') |>
  crop(rts_rep_rescale)
```

```{r}
# replace NAs in (country) name with nearest name
filled_names = world_rast |>
  focal(51, median, na.policy = 'only', na.rm = TRUE) |>
  round() |>
  mask(rts_rep_rescale[['alt']])

levels(filled_names) = cats(world_rast)

filled_names_df = filled_names |>
  as.data.frame(xy = TRUE, cell = TRUE, na.rm = TRUE)

# Make sure to "Free unused R memory" after running
gc()

nrow(filled_names_df)
# rts_rep_rescale = c(filled_names, rts_rep_rescale)
```

```{r}
rts_rep_rescale_df = filled_names_df |>
  right_join(rts_rep_rescale_df, by = c('x', 'y', 'cell'))
```

```{r}
rts_rep_rescale_df |>
  filter(is.na(name)) |>
  summarise(n())
```

# Run PCA

Ensure there are no NAs in the data
```{r}
rts_rep_rescale_df = rts_rep_rescale_df |>
  drop_na()
```

```{r}
# pca = prcomp(
#   x = rts_rep_rescale_df |>
#     select(-c(x, y, cell, name))
# )
# 
# saveRDS(pca,
#         './pca/pca.Rdata')
pca = readRDS('./pca/pca.Rdata')

summary(pca)
```

```{r}
pca_var = tibble(pc =seq(1, 30),
          variance = test$importance[2,])

ggplot(pca_var, aes(x = pc, y = variance)) +
  geom_line() +
  geom_point() +
  scale_x_continuous(name = 'Principal Component') +
  scale_y_continuous(name = 'Variance Explained')

ggsave('./figures/pca_variance.jpg',
       height = 3, width = 4)
```

```{r}
autoplot(
  pca,
  data = rts_rep_rescale_df,
  color = 'name',
  loadings = TRUE, 
  loadings.colour = 'black',
  loadings.label = TRUE, 
  loadings.label.size = 3,
  loadings.label.colour = 'black',
  alpha = 0.2
) +
  scale_color_viridis(discrete = TRUE) +
  coord_fixed() +
  theme(legend.title = element_blank())

gc()

# ggsave('./figures/pca_1_2.pdf',
#        height = 6.5,
#        width = 6.5)
# ggsave('./figures/pca_1_2.jpg',
#        height = 6.5,
#        width = 6.5)
```

```{r}
autoplot(
  pca,
  data = rts_rep_rescale_df,
  x = 1,
  y = 3,
  color = 'name',
  loadings = TRUE, 
  loadings.colour = 'black',
  loadings.label = TRUE, 
  loadings.label.size = 3,
  loadings.label.colour = 'black',
  alpha = 0.2
) +
  scale_color_viridis(discrete = TRUE) +
  coord_fixed() +
  theme(legend.title = element_blank())

gc()

# ggsave('./figures/pca_1_3.pdf',
#        height = 6.5,
#        width = 6.5)
# ggsave('./figures/pca_1_3.jpg',
#        height = 6.5,
#        width = 6.5)
```

```{r}
autoplot(
  pca,
  data = rts_rep_rescale_df,
  x = 2,
  y = 3,
  color = 'name',
  loadings = TRUE, 
  loadings.colour = 'black',
  loadings.label = TRUE, 
  loadings.label.size = 3,
  loadings.label.colour = 'black',
  alpha = 0.2
) +
  scale_color_viridis(discrete = TRUE) +
  coord_fixed() +
  theme(legend.title = element_blank())

gc()

# ggsave('./figures/pca_2_3.pdf',
#        height = 6.5,
#        width = 6.5)
# ggsave('./figures/pca_2_3.jpg',
#        height = 6.5,
#        width = 6.5)
```


# Maps of Principal Components

```{r}
rts_rep_pca = rts_rep_rescale_df |>
  cbind.data.frame (pca[['x']])
```

```{r}
pca_rast = rts_rep_rescale
pca_rast[rts_rep_pca$cell] = rts_rep_pca[, seq(ncol(rts_rep_pca) - 29, ncol(rts_rep_pca))]

names(pca_rast) = colnames(rts_rep_pca)[seq(ncol(rts_rep_pca) - 29, ncol(rts_rep_pca))]

# writeRaster(pca_rast,
#             './pca/pca.tif',
#             overwrite = TRUE)
```

```{r}
ggplot() +
  geom_spatraster(data = pca_rast) +
  scale_fill_viridis(name = 'PC1',
                     na.value = 'transparent',
                     limits = c(-5, 5),
                     oob = scales::squish) +
  facet_wrap(~lyr)

# ggsave('./figures/pca_map_all.jpg',
#        height = 6.5,
#        width = 6.5)
# ggsave('./figures/pca_map_all.pdf',
#        height = 6.5,
#        width = 6.5)
```

```{r}
ggplot() +
  geom_spatraster(data = pca_rast |>
                    subset('PC1')) +
  geom_sf(data = world |>
         filter(name %in% as.character(filled_names_df$name)) |>
           st_transform(3413) |>
           st_crop(ext(pca_rast)), 
          aes(geometry = geometry),
          inherit.aes = FALSE,
          fill = 'transparent') +
  scale_fill_viridis(name = 'PC1',
                     na.value = 'transparent',
                     limits = c(-5, 5),
                     oob = scales::squish) +
  facet_wrap(~lyr) +
  coord_sf(expand = FALSE)

# ggsave('./figures/pca_map_pc1.jpg',
#        height = 5.75,
#        width = 6.5)
# ggsave('./figures/pca_map_pc1.pdf',
#        height = 5.75,
#        width = 6.5)
```

```{r}
ggplot() +
  geom_spatraster(data = pca_rast |>
                    subset('PC2')) +
  geom_sf(data = world |>
         filter(name %in% as.character(filled_names_df$name)) |>
           st_transform(3413) |>
           st_crop(ext(pca_rast)), 
          aes(geometry = geometry),
          inherit.aes = FALSE,
          fill = 'transparent') +
  scale_fill_viridis(name = 'PC2',
                     na.value = 'transparent',
                     limits = c(-5, 5),
                     oob = scales::squish) +
  facet_wrap(~lyr) +
  coord_sf(expand = FALSE)

# ggsave('./figures/pca_map_pc2.jpg',
#        height = 5.75,
#        width = 6.5)
# ggsave('./figures/pca_map_pc2.pdf',
#        height = 5.75,
#        width = 6.5)
```

```{r}
ggplot() +
  geom_spatraster(data = pca_rast |>
                    subset('PC3')) +
  geom_sf(data = world |>
         filter(name %in% as.character(filled_names_df$name)) |>
           st_transform(3413) |>
           st_crop(ext(pca_rast)), 
          aes(geometry = geometry),
          inherit.aes = FALSE,
          fill = 'transparent') +
  scale_fill_viridis(name = 'PC3',
                     na.value = 'transparent',
                     limits = c(-5, 5),
                     oob = scales::squish) +
  facet_wrap(~lyr) +
  coord_sf(expand = FALSE)

# ggsave('./figures/pca_map_pc3.jpg',
#        height = 5.75,
#        width = 6.5)
# ggsave('./figures/pca_map_pc3.pdf',
#        height = 5.75,
#        width = 6.5)
```
