---
title: "Study Extent"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

# Load Libraries
```{r}
library(sf)
library(tidyverse)
```


# Load Data
```{r}
tk_landscapes = st_read('./input_data/OlefeldtThermokarstMap/data/Circumpolar_Thermokarst_Landscapes.shp')
```
# Correct Invalid Geometries

```{r}
tk_landscapes = tk_landscapes %>%
  mutate(valid = st_is_valid(.)) %>%
  st_make_valid()
```

# First Look

```{r}
ggplot(tk_landscapes) +
  geom_sf(aes(fill = TKHP),
          color = NA)
```

# Union of Polygons

```{r}
tk_union = tk_landscapes |>
  st_buffer(dist = 500) |>
  st_union() |>
  st_sf() |>
  rename(geometry = 1)

# st_write(tk_union,
#          './input_data/OlefeldtThermokarstMap/study_extent_buff500_no_fill.shp')

# st_write(tk_union,
#          './input_data/OlefeldtThermokarstMap/study_extent_buff1000_no_fill.shp')
```

```{r}
ggplot(tk_union) +
  geom_sf(fill = 'transparent')
```

# Remove Holes

```{r}
tk_no_holes = tk_union %>%
  sfheaders::sf_remove_holes() %>%
  st_cast('POLYGON') %>%
  mutate(area = as.numeric(st_area(.))/1e+06) # area in km2
```

```{r}
ggplot(tk_no_holes) +
  geom_sf(fill = 'transparent')
```

```{r}
ggplot() +
  geom_sf(data = filter(tk_landscapes, valid == FALSE), 
          aes(geometry = geometry),
          fill = 'red',
          color = 'red') +
  geom_sf(data = tk_no_holes, 
          aes(geometry = geometry),
          color = 'black',
          fill = 'transparent',
          lwd = 0.25)
```

```{r}
test = tk_no_holes |>
  arrange(desc(area))

ggplot(test, aes(x = area)) +
  geom_histogram(color = 'gray35') +
  scale_x_log10() +
  scale_y_log10()

ggplot(filter(test, area >= 1e+05)) +
  geom_sf(fill = 'transparent')
```

```{r}
ggplot(filter(tk_no_holes, area <= 1)) +
  geom_sf(data = tk_no_holes, 
          aes(geometry = geometry),
          color = 'black',
          fill = 'transparent',
          lwd = 0.25) +
  geom_sf(color = 'red',
          fill = 'red')

ggplot(filter(tk_no_holes, area <= 5)) +
  geom_sf(data = tk_no_holes, 
          aes(geometry = geometry),
          color = 'black',
          fill = 'transparent',
          lwd = 0.25) +
  geom_sf(color = 'red',
          fill = 'red')
```

```{r}
st_write(tk_union,
         './input_data/OlefeldtThermokarstMap/study_extent_buff500.shp')
```

