---
title: "TerraClimate Merge and Reprojection"
author: "Heidi Rodenhizer"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(terra)
library(tidyverse)
```

```{r}
files = list.files('./input_data/TerraClimate/ee_downloads', 
                   full.names = TRUE,
                   pattern = 'tif$')
subsets = files |>
  map_chr(
    ~ str_split(
      str_split(.x, '/')[[1]][length(str_split(.x, '/')[[1]])],
      '-'
    )[[1]][1]
  ) |>
  unique()
```

```{r}
load_terraclimate = function(files, pattern) {
  subset = files[str_which(files, pattern)]
  print(subset)
  
  raster = subset |>
    map(~ rast(.x)) |>
    sprc() |>
    merge()
  
  return(raster)
}
```

```{r}
terraclimate = subsets |>
  map(~ load_terraclimate(files, .x)) |>
  rast()
```

```{r}
terraclimate = terraclimate %>%
  subset(str_which(names(.), 'b0', negate = TRUE))

names(terraclimate) = c(
  "tmax_max", 
  "precip_max", 
  "runoff_max", 
  "swe_max", 
  "soil_mean",
  "tmin_min", 
  "precip_b1",
  "runoff_b1",
  "precip_sum", 
  "runoff_sum", 
  "srad_sum", 
  "swe_b1",  
  "temp_seasonality", 
  "tmax_b1", 
  "tmin_b1"
  )
```

```{r}
terraclimate = terraclimate |>
  subset(c(
  "tmin_min", 
  "tmin_b1", 
  "tmax_max", 
  "tmax_b1",  
  "temp_seasonality", 
  "precip_max", 
  "precip_sum", 
  "precip_b1",
  "swe_max", 
  "swe_b1", 
  "runoff_max", 
  "runoff_sum", 
  "runoff_b1",
  "soil_mean",
  "srad_sum"
  ))
```


```{r}
# writeRaster(terraclimate,
#             './input_data/TerraClimate/TerraClimateCompiled.tif')
```


